import { DataTable } from "@/components/DataTable";
import { FileUpload } from "@/components/FileUpload";
import { MapControls } from "@/components/MapControls";
import { MapVisualization } from "@/components/MapVisualization";
import { MetricsOverview } from "@/components/MetricsOverview";
import { CascadingFilters } from "@/components/CascadingFilters";
import { Button } from "@/components/ui/button";
import { YearFilter } from "@/components/YearFilter";
import { Select, SelectTrigger, SelectContent, SelectItem, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { ChartLine, Download, User } from "lucide-react";
import { useState, useEffect } from "react";
import { districts } from "../lib/districts";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuCheckboxItem,
} from "@/components/ui/dropdown-menu";

export default function Dashboard() {
  // Initialize all state variables at the top
  const [selectedYears, setSelectedYears] = useState<string[]>(['2022', '2023', '2024', '2025']);
  const [selectedMonths, setSelectedMonths] = useState<string[]>([]);
  const [selectedMakers, setSelectedMakers] = useState<string[]>([]);
  const [selectedRTOs, setSelectedRTOs] = useState<string[]>([]);
  const [selectedStates, setSelectedStates] = useState<string[]>([]);
  const [selectedDistricts, setSelectedDistricts] = useState<string[]>([]);
  const [viewMode, setViewMode] = useState<'heatmap' | 'markers' | 'clusters'>('markers');
  const [showLabels, setShowLabels] = useState(true);
  const [filteredSalesData, setFilteredSalesData] = useState<any[]>([]);

  // Clear sales data on page load
  useEffect(() => {
    fetch("/api/clear-sales-data", { method: "POST" });
  }, []);

  // Get unique states from districts
  const states = Array.from(new Set(districts.map(d => d.state))).sort();
  
  // Get districts for selected states
  const filteredDistricts = selectedStates.length > 0 
    ? districts.filter(d => selectedStates.includes(d.state)) 
    : [];

  const yearOptions = ["2022", "2023", "2024", "2025"];
  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  const makers = [
  "A-1 SUREJA INDUSTRIES",
  "ABZO MOTORS PVT LTD",
  "ADRIS ELECTRIC PVT LTD",
  "AFTEK MOTORS INDIA PVT LTD",
  "ALTIUS EV TECH PVT LTD",
  "AMO MOBILITY SOLUTIONS PVT LTD",
  "AMPERE VEHICLES PRIVATE LIMITED",
  "AMPERE VEHICLES PVT LTD",
  "ANCHI MOTORCYCLE  (IMPORTER: ECOTRINITY AUTOMOBILE",
  "ANCHI MOTORCYCLE (IMPORTER: EVNEXUS PVT. LTD.)",
  "ANCHI MOTORCYCLE (IMPORTER: YED ELECTRIC)",
  "ANCHI MOTORCYCLE(IMPORTER:GREEN FUEL ALTERNATIVES)",
  "ASHNNI MOTORS PVT LTD",
  "ATHER ENERGY LTD",
  "ATUMOBILE PVT LTD",
  "ATOMEX E-MOTORS INDIA PVT LTD",
  "BAILI MOTOR (IMPORTER:A B MOTOSS EV PVT LTD)",
  "BAJAJ AUTO LTD",
  "BATTRE ELECTRIC MOBLITY PVT LTD",
  "BENLING INDIA ENERGY AND TECHNOLOGY PVT LTD",
  "BGAUSS AUTO PRIVATE LIMITED",
  "BLIX CYCLES AND E-VEHICLES PVT LTD",
  "BMW INDIA PVT LTD",
  "BOOMA INNOVATIVE TRANSPORT SULUTIONS PVT LTD",
  "BOUNCE ELECTRIC 1 PVT LTD",
  "BMR EV INDUSTRIES PVT LTD",
  "BU4 AUTO PVT LTD",
  "CHANDANA CORPORATION",
  "CHETAK TECHNOLOGY LIMITED",
  "CHINA HAOCHEN (IMPORTER: ADMS MARKETING)",
  "CHINA HAOCHEN (IMPORTER:SLSR ELECTRO)",
  "CHONGQING CHARMING (IMPORTER: AYAAN ELECTRONICS).",
  "DAO EVTECH PRIVATE LIMITED",
  "DILLI ELECTRIC AUTO PVT LTD",
  "DONGMA VEHICLE (IMPORTER: MERCURY METALS)",
  "DURGA FILTERS PVT LTD",
  "E ROYCE MOTORS INDIA PVT LTD",
  "E-ASHWA AUTOMOTIVE (HS 2W) PVT LTD",
  "E-SPRINTO GREEN ENERGY PVT LTD",
  "ECO FUEL SYSTEMS (I) PVT LTD",
  "ECOBIT INTERNATIONAL(IMPORTER: JHEV MOTORS)",
  "ELECTRECA VEHICLES",
  "ELECTRIC ALLIANCE(IMPORTER: ELLYSIUM AUTOMOTIVES)",
  "ELECTROTHERM (INDIA) LIMITED",
  "ELEGO MOTORS PVT LTD",
  "ELTHOR ENERGY PRIVATE LIMITED",
  "ENIGMA AUTOMOBILES PVT LTD",
  "ENGTIAN ELECTRIC BIKE PVT LTD",
  "ESSEL ENERGY INFRA PVT LTD",
  "EXERVAL PVT LTD",
  "EVTRIC MOTORS PVT LTD",
  "EYAMAUTO MOBILITY PVT LTD",
  "FIADO INDUSTRIES PVT LTD",
  "FSTMOTO (IMPORTER: AUTOICARE INNOVATION)",
  "FSTMOTO INTERNATIONAL (IMPORTER: TEDI (INDIA))",
  "FUJIYAMA POWER INFRA PVT. LTD.",
  "GAURA ELECTRIC VEHICLES PVT LTD",
  "GODAWARI ELECTRIC MOTORS PVT LTD",
  "GOGORO (IMPORTER: GOGORO INDIA PRIVATE LTD)",
  "GOGORO INDIA PVT LTD",
  "GO GREEN EOT (ENERGY OF THINGS) PVT LTD",
  "GOLDENLION (IMPORTER:ELLYSIUM AUTOMOTIVES PVT LTD)",
  "GOREEN E-MOBILITY PVT LTD",
  "GREAVES ELECTRIC MOBILITY PVT LTD",
  "GUANGXI MEIBAO(IMPORTER: DYNAMO ELECTRIC)",
  "HAYASA E-MOBILITY (INDIA) PVT LTD",
  "HERO ELECTRIC VEHICLE PVT LTD",
  "HERO ELECTRIC VEHICLES PVT. LTD",
  "HERO HONDA MOTORS  LTD",
  "HERO MOTOCORP LTD",
  "HOMFEEL VEGH AUTOMOBILES PVT LTD",
  "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
  "HOP ELECTRIC MOBILITY PVT LTD",
  "HOUSTAN INNOVATION LLP",
  "HSU DRAGON (IMPORTER: BMR ELECTRIC)",
  "HSU DRAGON (IMPORTER: BMR EV INDUSTRIES)",
  "HSU DRAGON (IMPORTER: DARK FIGHT POWER PVT LTD)",
  "IGOWISE MOBILITY PVT LTD",
  "IRA EDUTECH PVT LTD",
  "IZANAU ELECTRIC LLP",
  "JIANGSU AIMA (IMPORTER: FUTURE EV)",
  "JIANGSU AIMA (IMPORTER: QUANTUM ENERGY)",
  "JIANGSU DALONG (IMPORTER: ENGTIAN ELECTRIC)",
  "JIANGSU DALONG (IMPORTER: KINGCHE MOBILITY)",
  "JIANGSU DALONG (IMPORTER: RILOX EV PVT LTD)",
  "JIANGSU DALONG (IMPORTER: SABOO TOR)",
  "JIANGSU DALONG (IMPORTER: TYLOS ELECTRIC VEHICLES)",
  "JIANGSU DALONG JIANHAO (IMPORTER: GREEN INDIA)",
  "JIANGSU DALONG JIANHAO (IMPORTER: MK FLYING)",
  "JIANGSU GUOWEI (IMPORTER: REVEAL ELECTRIC)",
  "JIANGSU GUOWEI (IMPORTER:ELECTRO-TECH)",
  "JIANGSU JINPENG (IMPORTER:RAFT MOTORS P. LTD)",
  "JIANGSU SUNHOU (IMPORTER: SABOO TOR)",
  "JIANGSU XINRI (IMPORTER: NISIKI TECHNOLOGIES)",
  "JIANGSU XINRI E-VEHICLE(IMPORTER SWIFT CUR.TECH.)",
  "JIANGSU ZHEENAIDA (IMPORTER: KLB GLOBAL)",
  "JIANGSU ZHONGXING (IMPORTER:SKANDAA AUTOMOTIVE)",
  "JITENDRA NEW EV-TECH PVT. LTD",
  "JEEVAA E-BIKE MFG PVT LTD",
  "JUNENG MOTORCYCLE (IMPORTER: ADMS MARKETING)",
  "JUNENG MOTORCYCLE (IMPORTER: ISCOOT MOTERS)",
  "JUNENG MOTORCYCLE (IMPORTER: JHEV MOTORS PVT LTD)",
  "JUNENG MOTORCYCLE TECH. (IMPORTER: DELTA AUTOCORP)",
  "KABIRA MOBILITY LLP",
  "KAINING (HONGKONG) (IMPORTER: BEST EV MOBILITY)",
  "KAINING (HONGKONG) (IMPORTER: BMR EV INDUSTRIES)",
  "KAINING (HONGKONG) (IMPORTER: COMPTECH MOTOCORP)",
  "KAINING (HONGKONG) (IMPORTER: ENIGMA AUTOMOBILES)",
  "KAINING (HONGKONG) (IMPORTER: ENERGY AUTOMOBILE)",
  "KAINING (HONGKONG) (IMPORTER: M/S IZANAU ELECTRIC)",
  "KAINING (HONGKONG) (IMPORTER: RAILES MOTO)",
  "KAINING (HONGKONG) (IMPORTER: TOXMO ELECTRIC)",
  "KAINING (HONGKONG) (IMPORTER: VOLTA EV PVT LTD)",
  "KLB KOMAKI PVT LTD",
  "KINETIC GREEN ENERGY & POWER SOLUTIONS LTD",
  "KYTE ENERGY PVT. LTD.",
  "LECTRIX E VEHICLES PVT LTD",
  "LI-IONS ELEKTRIK SOLUTIONS PVT LTD",
  "LIMA VEHICLE (IMPORTER: SARAOGI E-VENTURES)",
  "LIMA VEHICLE GROUP(IMPORTER: ROUTE & MARS EV LLP)",
  "LORDS AUTOMATIVE PVT LTD",
  "MAC INTERNATIONAL (IMPORTER: JHEV MOTORS PVT LTD)",
  "MAC INTERNATIONAL (IMPORTER: SUNDAK SOLAR)",
  "MAC INTERNATIONAL (IMPORTER:HONESTY)",
  "MAA LUXMI E-VEHICLES PVT. LTD.",
  "MAGNIOUS E MOBILITY PVT LTD",
  "MAULIRAJ INDUSTRIES LLP",
  "MATTER MOTOR WORKS PVT LTD",
  "MECPOWER MOBILITY PVT. LTD.",
  "MEW ELECTRICALS LIMITED",
  "MICROAUTOTECH PVT. LTD.",
  "MINI METRO EV L.L.P",
  "MIRAKLE 5 AUTOMOBILES PVT LTD",
  "MODIKA INTERNATIONAL (IMPORTER: FRANKLIN EV)",
  "MOTOVOLT MOBILITY PVT LTD",
  "M2GO ELECTRIC VEHICLE PVT LTD",
  "NANJING VMOTO (IMPORTER: FORTUNEV)",
  "NDS ECO MOTORS PVT LTD",
  "NINGBO SANJIANG (IMPORTER: VABRO EVTECH)",
  "NISIKI TECHNOLOGIES PVT LTD",
  "NUMEROS MOTORS PVT LTD",
  "OBEN ELECTRIC VEHICLES PVT LTD",
  "ODYSSE ELECTRIC VEHICLES PVT LTD",
  "OLA ELECTRIC TECHNOLOGIES PVT LTD",
  "OMJAY EV LIMITED",
  "OTHERS",
  "OZOTEC AUTOMOBILE PRIVATE LIMITED",
  "PATNA",
  "PORFITEL TECHNOLOGY (IMPORTER: AERORIDE)",
  "PORWAL ELECTRIC",
  "PUR ENERGY PVT LTD",
  "QICHENG VEHICLE (IMPORTER: AUTOICARE INNOVATION)",
  "QUANTUM ENERGY LTD.",
  "QOOKEE TECHNOLOGIES (IMPORTER:VIKEBIKE INDIA)",
  "RAPTEE ENERGY PVT LTD",
  "RGM BUSINESS PLUS PVT LTD",
  "REGENERATION E BIKES",
  "REVOLT INTELLICORP PVT LTD",
  "RGM BUSINESS PLUS PVT LTD",
  "RIVER MOBILITY PVT LTD",
  "ROWWET MOBILITY PVT LTD",
  "SBTEK E MOTO PVT LTD",
  "SEEKA E MOTORS PVT LTD",
  "SHRI BARSANA E-VEHICLES PVT LTD",
  "SHEMA E- VEHCILE & SOLAR PVT LTD",
  "SIMPLEENERGY PVT LTD",
  "SMAP VEHICLES (IMPORTER: ELEGO MOTORS)",
  "SMARDA INDUSTRY (IMPORTER: RHYNO)",
  "SOKUDO ELECTRIC INDIA PVT LTD",
  "SRIVARU MOTORS PVT LTD",
  "SUZUKI MOTORCYCLE INDIA PVT LTD",
  "SUMEC CO LTD (IMPORTER: ROUTE & MARS EV LLP)",
  "SUPERTECH EV LIMITED",
  "SUPERECO AUTOMOTIVE CO",
  "THUKRAL ELECTRIC BIKES PVT LTD",
  "TORK MOTORS PVT LTD",
  "TUNWAL E MOTORS PVT LTD",
  "TUNWAL E MOTORS PVT LTD.",
  "TYST DRIVE INDIA PVT LTD",
  "TVS MOTOR COMPANY LTD",
  "ULTRAVIOLETTE AUTOMOTIVE PVT LTD",
  "UK MODEN (IMPORTER: ELTHOR EV PVT LTD)",
  "UNIQUE INTERNATIONAL",
  "VELOCIFERO (IMPORTER: KAWVELOCE MOTORS PVT LTD)",
  "VINTAGE VEHICLES",
  "WARDWIZARD INNOVATIONS & MOBILITY LIMITED",
  "WARIVO MOTOR INDIA PVT LTD",
  "WHITE CARBON MOTORS PVT LTD",
  "WUXI DAYANG (IMPORTER: MOVAENERGY PRIVATE LIMITED)",
  "WUXI DAYANG ELECTRIC (IMPORTER: ABZO MOTORS)",
  "WUXI DONGMA (IMPORTER: DYNAM PRECISION)",
  "WUXI JIYAYI (IMPORTER: IZANAU ELECTRIC LLP)",
  "WUXI MAYA (IMPORTER: DYNAMO ELECTRIC P. LTD.)",
  "WUXI NOOMA (IMPORTER: KKL HITECH EV)",
  "WUXI NOOMA (IMPORTER: SMARTNK  ELECTRIC VEHICLE)",
  "WUXI SAIGE (IMPORTER: CITIZEN CARE)",
  "WUXI SAIGE (IMPORTER: DM GREEN ENERGY)",
  "WUXI SAIGE (IMPORTER: E-VISHWA ELECTOBIKE)",
  "WUXI SAIGE (IMPORTER: GLORIOUS DIGITAL)",
  "WUXI SAIGE (IMPORTER: KKL HITECH EV)",
  "WUXI SAIGE (IMPORTER: NGAGE IMPEX)",
  "WUXI SAIGE (IMPORTER: WARIVO MOTOR)",
  "WUXI SAIGE (IMPORTER: ZELIO AUTO PVT.LTD.)",
  "WUXI SAIGE ELECTRIC (IMPORTER: DELTA AUTOCORP LLP)",
  "WUXI SHENGBAO (IMPORTER:ELECTRIC ONE ENERGY)",
  "WUXI SHENGBAO (IMPORTER:SHEMA E-VEHICLE)",
  "WUXI TENGHUI (IMPORTER: BOHRE ELECTRIC)",
  "WUXI TENGHUI (IMPORTER: CAL-ON INDUSTRIES)",
  "WUXI TENGHUI (IMPORTER: FLYCON MOTORS)",
  "WUXI TENGHUI (IMPORTER: FRANKLIN EV INDIA)",
  "WUXI TENGHUI (IMPORTER: HOP ELECTRIC MOBILITY)",
  "WUXI TENGHUI (IMPORTER: JAIDKA POWER)",
  "WUXI TENGHUI (IMPORTER: NXTMOBILITY ENERGY)",
  "WUXI TENGHUI (IMPORTER: RADHA MOBILITIES LLP)",
  "WUXI TENGHUI (IMPORTER: REMARK ELECTRIC)",
  "WUXI TENGHUI (IMPORTER: SEEKA E MOTORS)",
  "WUXI TENGHUI (IMPORTER: SUSHAMA MOTORS)",
  "WUXI TENGHUI (IMPORTER: WARIVO MOTOR)",
  "WUXI TENGHUI (IMPORTER: FLYCON MOTORS)",
  "WUXI TENGHUI INTERNATIONAL (IMPORTER: FEZORA)",
  "WUXI TENGHUI INTERNATIONAL (IMPORTER: FRANKLIN EV)",
  "WUXI TOURWE (IMPORTER: GOREEN E-MOBILITY)",
  "WUXI YIZHILING (IMPORTER: BMR EV INDUSTRIES)",
  "WUXI YIZHILING (IMPORTER: HOMFEEL VEGH)",
  "XIDAA MOTO PVT LTD",
  "YADEA TECHNOLOGY (IMPORTER: YULU BIKES)",
  "YANGGUANG LINGMU (IMPORTER: DAWNGATE BUSINESS)",
  "YANGGUANG LINGMU (IMPORTER: DURGA FILTERS)",
  "YANGGUANG LINGMU (IMPORTER: ECOINDIA)",
  "YANGGUANG LINGMU (IMPORTER: FLYCON MOTORS)",
  "YANGGUANG LINGMU (IMPORTER: REMARK ELECTRIC)",
  "YANGGUANG LINGMU (IMPORTER: XWLS ELECTRIC)",
  "YOUYAKU ELECTRIC (IMPORTER: HOUSTAN INNOVATION)",
  "YOUYAKU ELECTRIC (IMPORTER: IME VEHICLES PVT LTD)",
  "YOUYAKU ELECTRIC (IMPORTER: KRISHIKA EV INDIA)",
  "YOUYAKU ELECTRIC (IMPORTER: NEWTRON ELECTRIC)",
  "YOUYAKU ELECTRIC (IMPORTER: ONZO EV)",
  "YOUYAKU ELECTRIC (IMPORTER: POWORO PVT LTD)",
  "YOUYAKU ELECTRIC (IMPORTER: RIVALDO ELECTRIC)",
  "YOUYAKU ELECTRIC (IMPORTER: SASDAL ENTERPRISES)",
  "YOUYAKU ELECTRIC (IMPORTER: SHEMA E-VEHICLE)",
  "YOUYAKU ELECTRIC (IMPORTER: SMOBILITY EV)",
  "YOUYAKU ELECTRIC (IMPORTER: TES ELECTRIC)",
  "YOUYAKU ELECTRIC (IMPORTER: TVISI ELECTRIC)",
  "YOUYAKU ELECTRIC (IMPORTER:IME VEHICLES PVT LTD)",
  "YOUYAKU ELECTRIC (IMPORTER:ONZO EV)",
  "YOUYAKU ELECTRIC (IMPORTER: SMOBILITY EV)",
  "YOUYAKU ELECTRIC (IMPORTER: TVISI ELECTRIC)",
  "YOUYAKU ELECTRIC TECHNOLOGY (IMPORTER:JHEV MOTORS)",
  "ZAP (HK) (IMPORTER: IZANAU ELECTRIC)",
  "ZAP (IMPORTER:ELLYSIUM AUTOMOTIVES PVT LTD)",
  "ZELIO AUTO PVT LTD",
  "ZHONGHUALONG (IMPORTER: POWORO PVT LTD)",
  "ZHONGXING (IMPORTER:GREENO AUTOMOBILE)",
  "ZHEJIANG LUYUAN (IMPORTER: DYNAM EV TECH)",
  "ZHEJIANG TIANYING  (IMPORTER: NEWTRON ELECTRIC)"
].sort();

  const rtos = [
  "Aahwa   Gj30",
  "Abu Road Dto   Rj38",
  "Adilabad   Ap01",
  "Adoor Srto   Kl26",
  "Agra Rto   Up80",
  "Ahmedabad   Gj1",
  "Ahmedabad (Rural), Bawla Arto   Gj38",
  "Ahmedabad East   Gj27",
  "Aizawl Dto   Mz1",
  "Akbarpur(Ambedkar Nagar)   Up45",
  "Akluj   Mh45",
  "Alangudi Uo   Tn641",
  "Alangulam Uo   Tn644",
  "Alappuzha Rto   Kl4",
  "Alathur Srto   Kl49",
  "Aligarh Rto   Up81",
  "Alipore Rto   Wb19",
  "Alipurduar Rto   Wb69",
  "Almora Rto   Uk1",
  "Aluva Srto   Kl41",
  "Amalapuram Rta   Ap205",
  "Amarawati   Mh27",
  "Ambala City   Hr1",
  "Ambasamuthiram Uo   Tn611",
  "Ambattur Rto   Tn612",
  "Ambejogai   Mh44",
  "Ambur Uo   Tn628",
  "Amethi Arto   Up36",
  "Amrawati   Mh27",
  "Anakapalli Rta   Ap131",
  "Anand   Gj23",
  "Anantapur Rta   Ap2",
  "Anantnag Arto   Jk3",
  "Angamali Srto   Kl63",
  "Angul Rto   Od19",
  "Anuppur Dto   Mp65",
  "Arakkanam Uo   Tn609",
  "Arani Rto   Tn516",
  "Aranthangi Uo   Tn592",
  "Aravakurichi Uo   Tn632",
  "Ariyalur Rto   Tn61",
  "Arto Barbil   Od901",
  "Arto Office Rampur   Up22",
  "Aruppukottai Uo   Tn622",
  "Ashoknagar Dto   Mp67",
  "Assandh   Hr40",
  "Athani Arto   Ka71",
  "Attingal Rto   Kl16",
  "Attur Rto   Tn591",
  "Auraiya   Up79",
  "Aurangabad   Br26",
  "Avinashi Uo   Tn580",
  "Ayodhya Rto   Up42",
  "Azamgarh Rto   Up50",
  "Badaun   Up24",
  "Badwani Dto   Mp46",
  "Bagalkot Rto   Ka29",
  "Baghpat   Up17",
  "Bahadurgarh   Hr13",
  "Bahour   Py11",
  "Bahraich   Up40",
  "Baikunthpur Dto   Cg16",
  "Bailhongal Rto   Ka24",
  "Balaghat Dto   Mp50",
  "Balasore Rto   Od1",
  "Ballabgarh   Hr29",
  "Ballia   Up60",
  "Balod Dto   Cg24",
  "Baloda Bazar Dto   Cg22",
  "Balrampur   Up47",
  "Balrampur Dto   Cg30",
  "Bandarto   Up90",
  "Bandipora Arto   Jk15",
  "Bangaon Arto   Wb27",
  "Bantwala Arto   Ka70",
  "Barabanki Arto   Up41",
  "Baramati   Mh42",
  "Baramulla Arto   Jk5",
  "Baran Dto   Rj28",
  "Barara   Hr54",
  "Barasat Rto   Wb25",
  "Bardoli   Gj19",
  "Bareilly   Up25",
  "Bargarh Rto   Od17",
  "Barmer Dto   Rj4",
  "Barrackpore Arto   Wb23",
  "Baruipur Arto   Wb95",
  "Basavakalyan Arto   Ka56",
  "Basirhat Arto   Wb21",
  "Baska   As28",
  "Basti Rto   Up51",
  "Batlagundu Uo   Tn596",
  "Bawal   Hr81",
  "Beawar Dto   Rj36",
  "Beed   Mh23",
  "Behala Arto   Wb9",
  "Bellary Rto   Ka34",
  "Bemetara Dto   Cg25",
  "Bengaluru Central Rto   Ka1",
  "Bengaluru East Rto   Ka3",
  "Bengaluru North Rto   Ka4",
  "Bengaluru South Rto   Ka5",
  "Bengaluru West Rto   Ka2",
  "Betul Dto   Mp48",
  "Bhabhua   Br45",
  "Bhadohi(Sant Ravidas Nagar)   Up66",
  "Bhagalpur   Br10",
  "Bhandara   Mh36",
  "Bharatpur Rto   Rj5",
  "Bharuch   Gj16",
  "Bhavani Uo   Tn578",
  "Bhavnagar   Gj4",
  "Bhilkhiwind   Pb88",
  "Bhilwara Dto   Rj6",
  "Bhind Dto   Mp30",
  "Bhinmal Dto   Rj46",
  "Bhiwani   Hr16",
  "Bhiwari Dto   Rj40",
  "Bhopal Rto   Mp4",
  "Bhubaneswar Ii Rto   Od33",
  "Bhubaneswar Rto   Od2",
  "Bicholim Rto   Ga4",
  "Bidar Rto   Ka38",
  "Bijapur Dto   Cg20",
  "Bijapur Rto   Ka28",
  "Bijnor   Up20",
  "Bikaner Rto   Rj7",
  "Bilaspur Rto   Cg10",
  "Birbhum Rto   Wb53",
  "Bishnupur   Mn5",
  "Bishnupur Arto   Wb87",
  "Bokaro   Jh9",
  "Bolpur Arto   Wb47",
  "Bongaigaon   As19",
  "Botad   Gj33",
  "Boudh Rto   Od27",
  "Bulandshahar   Up13",
  "Buldhana   Mh28",
  "Bundi Dto   Rj8",
  "Burhanpur Dto   Mp68",
  "Buxur   Br44",
  "Cachar   As11",
  "Canacona Rto   Ga10",
  "Chalakkudy Srto   Kl64",
  "Chalisgaon   Mh52",
  "Chamba   Hp48",
  "Chamarajanagar Rto   Ka10",
  "Chamkaur Sahib   Pb71",
  "Champhai   Mz4",
  "Chandapura, Bengaluru Rto   Ka59",
  "Chandikhole Rto   Od4",
  "Chandra   Br4",
  "Chandrapur   Mh34",
  "Chandigarh Ut (Rla And Sta)   Ch1",
  "Changanacherry Srto   Kl33",
  "Chankhi Dadri   Hr19",
  "Chattarpur Arto   Mp16",
  "Chatra   Jh13",
  "Chengalpattu Rto   Tn19",
  "Chengannur Srto   Kl30",
  "Chennai (Central) Rto   Tn1",
  "Chennai (East) Rto   Tn4",
  "Chennai (North East) Rto   Tn3",
  "Chennai (North) Rto   Tn5",
  "Chennai (South East) Rto   Tn6",
  "Chennai (South West) Rto   Tn10",
  "Chennai (South) Rto   Tn7",
  "Chennai (West) Rto   Tn9",
  "Cherthala Srto   Kl32",
  "Cheyyar Uo   Tn635",
  "Chhatrapati Sambhajinagar   Mh20",
  "Chhindwara Arto   Mp28",
  "Chhotaudaipur   Gj34",
  "Chickaballapur Rto   Ka40",
  "Chikamanglur Rto   Ka18",
  "Chikkodi Rto   Ka23",
  "Chilakaluripeta Mvi Office   Ap307",
  "Chintamani Arto   Ka67",
  "Chintoor   Ap905",
  "Chirala Uo   Ap127",
  "Chirang   As26",
  "Chittoor Rta   Ap3",
  "Chittorgarh Rto   Rj9",
  "Chomu Dto   Rj41",
  "Chopal   Hp8",
  "Chuwari   Hp57",
  "Coimbatore (Central) Rto   Tn66",
  "Coimbatore (North) Rto   Tn38",
  "Coimbatore (South) Rto   Tn37",
  "Coimbatore (West) Rto   Tn99",
  "Contai Arto   Wb31",
  "Coochbehar Rto   Wb63",
  "Cuddalore Rto   Tn31",
  "Cuddapah Rta   Ap4",
  "Cuttack Rto   Od5",
  "Dabwali   Hr25",
  "Dahod   Gj20",
  "Dakshin Dinajpur Rto   Wb61",
  "Damoh Dto   Mp34",
  "Dantewada Dto   Cg18",
  "Darbhanga   Br7",
  "Darsi Uo   Ap427",
  "Datia Dto   Mp32",
  "Dausa Rto   Rj29",
  "Davanagere Rto   Ka17",
  "Dehra   Hp36",
  "Dehradun Rto   Uk7",
  "Deogarh Rto   Od28",
  "Deoghar   Jh15",
  "Deoria   Up52",
  "Devanahalli Arto   Ka43",
  "Dewas Dto   Mp41",
  "Dhalai Dto   Tr4",
  "Dhamtari Dto   Cg5",
  "Dhar Arto   Mp11",
  "Dharamshala   Hp39",
  "Dharampur   Hp86",
  "Dharapuram Rto   Tn594",
  "Dharmapuri Rto   Tn29",
  "Dharashiv   Mh25",
  "Dharbandora Rto   Ga12",
  "Dheera   Hp96",
  "Dhemaji   As22",
  "Dhenkanal Rto   Od6",
  "Dhule   Mh18",
  "Diamond Harbour Arto   Wb97",
  "Dimapur Dto   Nl7",
  "Dindigul Rto   Tn57",
  "Dindori Dto   Mp52",
  "Diu   Dd2",
  "Doda Arto   Jk6",
  "Dudh Sadhan   Pb83",
  "Dudu Dto   Rj47",
  "Durg Rto   Cg7",
  "Durgapore Arto   Wb39",
  "Dwarka   Dl9",
  "Dy Regional Transport Office, Hingoli   Mh38",
  "Dy Rto Ratnagiri   Mh8",
  "Electronic City Rto   Ka51",
  "Ellnabad   Hr44",
  "Erode (West) Rto   Tn86",
  "Erode Rto   Tn33",
  "Ernakulam Rto   Kl7",
  "Etah   Up82",
  "Etawah   Up75",
  "Faridabad   Hr51",
  "Farrukhabad   Up76",
  "Fathepur   Hp88",
  "Fatehabad   Hr22",
  "Fatehgarh Sahib   Pb23",
  "Fazilka   Pb22",
  "Ferozabad   Up83",
  "Ferozepur   Pb5",
  "Ferozepur Zirkha   Hr28",
  "Gadag Rto   Ka26",
  "Gadchiroli   Mh33",
  "Gajapati Rto   Od20",
  "Gajuwaka Rta   Ap231",
  "Ganaur   Hr42",
  "Ganderbal Arto   Jk16",
  "Gandhinagar   Gj18",
  "Ganjam Rto   Od7",
  "Garhwa   Jh14",
  "Gariyaband Dto   Cg23",
  "Gaurela Pendra Marwahi Dto   Cg31",
  "Gaya   Br2",
  "Ghatal Arto   Wb50",
  "Ghaziabad   Up14",
  "Ghazipur   Up61",
  "Ghumarvi   Hp23",
  "Gingee Uo   Tn627",
  "Giridih   Jh11",
  "Goalpara   As18",
  "Godda   Jh17",
  "Gohana   Hr11",
  "Gohar   Hp32",
  "Gokak Arto   Ka49",
  "Golaghat   As5",
  "Gonda   Up43",
  "Gondhia   Mh35",
  "Gopichettipalayam Rto   Tn36",
  "Gorakhpur Rto   Up53",
  "Gudiwada Rta   Ap116",
  "Gudiyatham Uo   Tn514",
  "Gudur Rta   Ap226",
  "Gulha   Hr9",
  "Gummidipoondi Uo   Tn625",
  "Gumla   Jh7",
  "Guna Dto   Mp8",
  "Guntakal Uo   Ap202",
  "Guntur Rta   Ap7",
  "Guru Har Sahai   Pb77",
  "Guruvayur Srto   Kl46",
  "Gwalior Rto   Mp7",
  "Haldia Arto   Wb32",
  "Haldwani Rto   Uk4",
  "Hailakandi   As24",
  "Hamirpur   Hp22",
  "Hamirpur(Up)   Up91",
  "Hansi   Hr21",
  "Hapur   Up37",
  "Harda Dto   Mp47",
  "Hardoi   Up30",
  "Haridwar Arto   Uk8",
  "Harur Uo   Tn527",
  "Haryana Head Office Chd   Hr70",
  "Hassan Rto   Ka13",
  "Hathras   Up86",
  "Haveri Rto   Ka27",
  "Hazaribag   Jh2",
  "Hindupur Rta   Ap102",
  "Hisar   Hr20",
  "Hodel   Hr50",
  "Honnavar Arto   Ka47",
  "Hooghly Rto   Wb15",
  "Hospet Rto   Ka35",
  "Hosur Rto   Tn70",
  "Howrah Rto   Wb11",
  "Hunsur Arto   Ka45",
  "I P Estate   Dl2",
  "Ichalkaranji   Mh51",
  "Idukki Rto   Kl6",
  "Illuppur Uo   Tn629",
  "Imphal East   Mn6",
  "Imphal West   Mn1",
  "Indore Rto   Mp9",
  "Irinjalakuda Srto   Kl45",
  "Iritty Srto   Kl78",
  "Islampur Arto   Wb91",
  "Itanagar Capital Region   Ar1",
  "Itchapuram Mvi Office   Ap130",
  "Jabalpur Rto   Mp20",
  "Jagadhari   Hr2",
  "Jagatsinghpur Rto   Od21",
  "Jaggayyapet Uo   Ap616",
  "Jaipur (First) Rto   Rj14",
  "Jaipur (Second) Rto   Rj59",
  "Jaisalmer Dto   Rj15",
  "Jaisingpur   Hp56",
  "Jajpur Rto   Od34",
  "Jalana   Mh21",
  "Jalandhar   Pb8",
  "Jalgaon   Mh19",
  "Jalpaiguri Rto   Wb71",
  "Jamkhandi Arto   Ka48",
  "Jamnagar   Gj10",
  "Jamtara   Jh21",
  "Jangareddygudem Rta   Ap237",
  "Jangipur Arto   Wb93",
  "Janjgir Champa Dto   Cg11",
  "Janakpuri   Dl4",
  "Jaunpur   Up62",
  "Jawali   Hp54",
  "Jhandutta   Hp89",
  "Jhargram Rto   Wb49",
  "Jhawar   Pb61",
  "Jhajhar   Hr14",
  "Jhalawar Dto   Rj17",
  "Jhansi Rto   Up93",
  "Jharsuguda Rto   Od23",
  "Jhunjhunu Dto   Rj18",
  "Jind   Hr31",
  "Jnanabharathi Rto   Ka41",
  "Jodhpur Rto   Rj19",
  "Joginder Nagar   Hp29",
  "Jorhat   As3",
  "Junagadh   Gj11",
  "K G F Arto   Ka8",
  "Kachchh   Gj12",
  "Kachchh East   Gj39",
  "Kaithal   Hr8",
  "Kalahandi Rto   Od8",
  "Kalimpong Rto   Wb78",
  "Kalna Arto   Wb43",
  "Kalyani Arto   Wb89",
  "Kalyan   Mh5",
  "Kalayat   Hr83",
  "Kalpa   Hp25",
  "Kandukur Mvi Office   Ap227",
  "Kangeyam Uo   Tn593",
  "Kangra   Hp40",
  "Kanhangad Srto   Kl60",
  "Kanjirappally Srto   Kl34",
  "Kannauj   Up74",
  "Kannur Rto   Kl13",
  "Kanpur Dehat   Up77",
  "Kanpur Nagar   Up78",
  "Karaikal   Py2",
  "Karaikudi Uo   Tn602",
  "Karimganj   As10",
  "Karnal   Hr5",
  "Karoli Dto   Rj34",
  "Karunagappally Srto   Kl23",
  "Karur Rto   Tn47",
  "Karwar Rto   Ka30",
  "Kasargode Rto   Kl14",
  "Kasba Arto   Wb5",
  "Kashipur Arto   Uk18",
  "Katihar   Br39",
  "Katni Arto   Mp21",
  "Kattakada Srto   Kl74",
  "Katwa Arto   Wb75",
  "Kaushambi   Up73",
  "Kavali Uo   Ap326",
  "Kawardha Dto   Cg9",
  "Kayamkulam Srto   Kl29",
  "Kazhakuttom Srto   Kl22",
  "Kekri Dto   Rj48",
  "Kendrapara Rto   Od29",
  "Keonjhar Rto   Od9",
  "Khagaria   Br34",
  "Khamgaon   Mh56",
  "Khambhaliya   Gj37",
  "Khandwa Arto   Mp12",
  "Khargone Arto   Mp10",
  "Kharagpur Arto   Wb35",
  "Kheda   Gj7",
  "Khetri Dto   Rj53",
  "Khordha Arto   Od201",
  "Khunti   Jh23",
  "Kishanganj   Br37",
  "Kishangarh Dto   Rj42",
  "Kishtwar Arto   Jk17",
  "Kodagu Rto   Ka12",
  "Koderma   Jh12",
  "Kodungallur Srto   Kl47",
  "Koduvally Srto   Kl57",
  "Koilandy Srto   Kl56",
  "Kolhapur   Mh9",
  "Kolkata (Central) Rto   Wb1",
  "Kollam Rto   Kl2",
  "Kondagaon Dto   Cg27",
  "Kondotty Srto   Kl84",
  "Konni Srto   Kl83",
  "Koraput Rto   Od10",
  "Korba Dto   Cg12",
  "Kotdwar Arto   Uk15",
  "Kothamangalam Srto   Kl44",
  "Kottarakkara Srto   Kl24",
  "Kottayam Rto   Kl5",
  "Kotputali Dto   Rj32",
  "Kovilpatti Rto   Tn607",
  "Kozhikode Rto   Kl11",
  "Krishnagiri Rto   Tn24",
  "Krishnarajapuram Rto   Ka53",
  "Kulgam Arto   Jk18",
  "Kulithali Uo   Tn585",
  "Kulu   Hp34",
  "Kumarapalayam Rto   Tn638",
  "Kumbakonam Rto   Tn68",
  "Kundrathur Rto   Tn85",
  "Kunnathur Srto   Kl61",
  "Kupwara Arto   Jk9",
  "Kurnool Rta   Ap21",
  "Kuttanadu Srto   Kl66",
  "Lakhimpur   As7",
  "Lakhimpur Kheri   Up31",
  "Lakhisarai   Br53",
  "Lalkudi Uo   Tn631",
  "Lalitpur   Up94",
  "Latehar   Jh19",
  "Leh Arto   La2",
  "Lohardaga   Jh8",
  "Loni Road   Dl5",
  "Ludhiana   Pb10",
  "Lunglei   Mz2",
  "Lunavada   Gj35",
  "Machilipatnam Rta   Ap216",
  "Macherla Mvi Office   Ap407",
  "Madhugiri, Tumakuru Arto   Ka64",
  "Madurai (Central) Rto   Tn64",
  "Madurai (North) Rto   Tn59",
  "Madurai (South) Rto   Tn58",
  "Madurantagam Uo   Tn508",
  "Mahanagar Arto Lucknow (Up321)   Up321",
  "Maharajganj   Up56",
  "Mahasamund Dto   Cg6",
  "Mahendergarh   Hr34",
  "Mahoba   Up95",
  "Mainpuri   Up84",
  "Malappuram Rto   Kl10",
  "Malda Rto   Wb65",
  "Malegaon   Mh41",
  "Mall Road   Dl1",
  "Mallappally Srto   Kl28",
  "Malkanagiri Rto   Od30",
  "Mananthavady Srto   Kl72",
  "Manaparai Uo   Tn584",
  "Mandapeta Uo   Ap405",
  "Mandla Dto   Mp51",
  "Mandsaur Arto   Mp14",
  "Mangalore Rto   Ka19",
  "Manmangalam Uo   Tn637",
  "Mannargudi Uo   Tn588",
  "Mannarghat Srto   Kl50",
  "Mapusa Rto   Ga3",
  "Margao Rto   Ga8",
  "Markapur Uo   Ap327",
  "Marthandam Rto   Tn75",
  "Mathabhanga Arto   Wb85",
  "Mathura   Up85",
  "Mattancherry Srto   Kl43",
  "Mau   Up54",
  "Mavelikkara Srto   Kl31",
  "Mayiladuthurai Rto   Tn589",
  "Mayurbhanj Rto   Od11",
  "Mayur Vihar   Dl7",
  "Meenambakkam Rto   Tn22",
  "Meerut Rto   Up15",
  "Mehsana   Gj2",
  "Melur Uo   Tn600",
  "Mettupalayam Rto   Tn40",
  "Mettur Rto   Tn590",
  "Mira Bhayandar   Mh58",
  "Mirzapur Rto   Up63",
  "Modasa   Gj31",
  "Moga   Pb29",
  "Moradabad   Up21",
  "Morbi   Gj36",
  "Morena Dto   Mp6",
  "Morigaon   As21",
  "Motihari   Br5",
  "Muktsar Sahib   Pb30",
  "Mumbai (Central)   Mh1",
  "Mumbai (East)   Mh3",
  "Mumbai (West)   Mh2",
  "Mungeli Dto   Cg28",
  "Munger   Br8",
  "Murshidabad Rto   Wb57",
  "Musuri Uo   Tn621",
  "Muzaffarnagar   Up12",
  "Muzaffarpur   Br6",
  "Mysuru East Rto   Ka55",
  "Mysuru West Rto   Ka9",
  "Nadia Rto   Wb51",
  "Nagaon   As2",
  "Nagapattinam Rto   Tn51",
  "Nagaur Dto   Rj21",
  "Nagercoil Rto   Tn74",
  "Nagpur (East)   Mh49",
  "Nagpur (Rural)   Mh40",
  "Nagpur (U)   Mh31",
  "Nahan   Hp18",
  "Namakkal (North) Rto   Tn28",
  "Namakkal (South) Rto   Tn88",
  "Nanded   Mh26",
  "Nandigama Rta   Ap316",
  "Nandurbar   Mh39",
  "Nandyal Rta   Ap121",
  "Nanmanda Srto   Kl76",
  "Narasaraopet Rta   Ap107",
  "Narsipatnam Mvi Office   Ap331",
  "Narsinghpur Dto   Mp49",
  "Narwana   Hr32",
  "Navsari   Gj21",
  "Nawarangpur Rto   Od24",
  "Nayagarh Rto   Od25",
  "Nedumangadu Srto   Kl21",
  "Neemuch Dto   Mp44",
  "Nellore Rta   Ap26",
  "Neyveli Uo   Tn562",
  "Neyyattinkara Srto   Kl20",
  "Nilambur Srto   Kl71",
  "Noida   Up16",
  "Nohar Dto   Rj49",
  "Nokha Dto   Rj50",
  "North Parur Srto   Kl42",
  "North Tripura Dto   Tr5",
  "Nuapada Rto   Od26",
  "Nuzvid Uo   Ap416",
  "Oddanchatram Uo   Tn595",
  "Omalure Uo   Tn535",
  "Ooty Rto   Tn43",
  "Orai   Up92",
  "Ottappalam Srto   Kl51",
  "Padrauna(Kushi Nagar)   Up57",
  "Paderu Rta   Ap41",
  "Palacode Uo   Tn616",
  "Palakole Uo   Ap637",
  "Palakonda Rta   Ap230",
  "Palamaner Mvi Office   Ap303",
  "Palampur   Hp37",
  "Palani Rto   Tn597",
  "Pali Rto   Rj22",
  "Palwal   Hr30",
  "Panaji Rto   Ga7",
  "Panchkula   Hr3",
  "Panchmahal   Gj17",
  "Panipat   Hr6",
  "Panruti Uo   Tn626",
  "Panvel   Mh46",
  "Panna Dto   Mp35",
  "Parbhani   Mh22",
  "Parvathipuram Rto Office   Ap135",
  "Paschim Burdwan Rto   Wb37",
  "Paschim Midnapore Rto   Wb33",
  "Patan   Gj24",
  "Pathanamthitta Rto   Kl3",
  "Pathankot   Pb35",
  "Pathanapuram Srto   Kl80",
  "Patiala   Pb11",
  "Pattukottai Unit Office   Tn587",
  "Pauri Rto   Uk12",
  "Pernem Rto   Ga11",
  "Perumbavur Srto   Kl40",
  "Phalodi Dto   Rj43",
  "Phaltan   Mh53",
  "Phulbani Rto   Od12",
  "Pilibhit   Up26",
  "Pipar City Dto   Rj54",
  "Pithoragarh Arto   Uk5",
  "Ponda Rto   Ga5",
  "Poonamallee Rto   Tn511",
  "Poonch Arto   Jk12",
  "Porbandar   Gj25",
  "Port Blair Dto   An1",
  "Prakasam Rta   Ap27",
  "Pratapgarh   Up72",
  "Pratapgarh Dto   Rj35",
  "Prayagraj Rto   Up70",
  "Proddutur Rta   Ap204",
  "Puducherry   Py1",
  "Pudukottai Rto   Tn55",
  "Pulivendula Mvi Office   Ap304",
  "Pulwama Arto   Jk13",
  "Pune   Mh12",
  "Punganur Uo   Ap113",
  "Puri Rto   Od13",
  "Purnea   Br11",
  "Purulia Rto   Wb55",
  "Puttur Rto   Ka21",
  "Pvd Kolkata   Wb1",
  "Quepem Rto   Ga9",
  "Raghunathpur Arto   Wb81",
  "Raibareilly   Up33",
  "Raichur Rto   Ka36",
  "Raigarh Dto   Cg13",
  "Raipur Rto   Cg4",
  "Rairangpur Arto   Od111",
  "Raisen Dto   Mp38",
  "Rajahmundry Rta   Ap105",
  "Rajapalayam Uo   Tn643",
  "Rajgarh   Hp16",
  "Rajgarh Dto   Mp39",
  "Rajkot   Gj3",
  "Rajouri Arto   Jk11",
  "Rajouri Garden   Dl10",
  "Rajsamand Dto   Rj30",
  "Ramachandrapuram Uo   Ap605",
  "Ramanagar Rto   Ka42",
  "Ramanathapuram Rto   Tn65",
  "Ramanattukara (Feroke) Srto   Kl85",
  "Ramganjmandi Dto   Rj33",
  "Ramgarh   Jh24",
  "Ramnagar Arto   Uk19",
  "Rampurhat Arto   Wb45",
  "Ranchi   Jh1",
  "Rani Srto   Kl62",
  "Ranibennur Arto   Ka68",
  "Ranipet Rto   Tn73",
  "Rasipuram Uo   Tn526",
  "Ratlam Dto   Mp43",
  "Ravulapalem Uo   Ap705",
  "Rayachoti Mvi Office   Ap504",
  "Raygada Rto   Od18",
  "Redhills Rto   Tn18",
  "Regional Transport Office Belagavi   Ka22",
  "Regional Transport Office Rampachodavaram   Ap141",
  "Rewa Rto   Mp17",
  "Rewari   Hr36",
  "Rishikesh Arto   Uk14",
  "Rla Amb   Hp19",
  "Rla Baijnath   Hp53",
  "Rla Balh   Hp82",
  "Rla Bangana   Hp78",
  "Rla Barsar   Hp21",
  "Rla Bhoranj   Hp74",
  "Rla Bilaspur   Hp24",
  "Rla Chopal   Hp8",
  "Rla Chuwari   Hp57",
  "Rla Dehra   Hp36",
  "Rla Dharampur   Hp86",
  "Rla Dharamshala   Hp39",
  "Rla Dheera   Hp96",
  "Rla Fathepur   Hp88",
  "Rla Gagret   Hp101",
  "Rla Ghumarvi   Hp23",
  "Rla Gohar   Hp32",
  "Rla Hamirpur   Hp22",
  "Rla Haroli   Hp80",
  "Rla Indora   Hp97",
  "Rla Jaisingpur   Hp56",
  "Rla Jawalaji   Hp83",
  "Rla Jawali   Hp54",
  "Rla Jhandutta   Hp89",
  "Rla Joginder Nagar   Hp29",
  "Rla Kalpa   Hp25",
  "Rla Kangra   Hp40",
  "Rla Kasauli   Hp98",
  "Rla Kotli   Hp102",
  "Rla Kulu   Hp34",
  "Rla Manali   Hp58",
  "Rla Mandi   Hp33",
  "Rla Nadaun   Hp55",
  "Rla Nagrota Bagwan   Hp94",
  "Rla Nahan   Hp18",
  "Rla Nalagarh   Hp12",
  "Rla Nurpur   Hp38",
  "Rla Pachhad   Hp100",
  "Rla Palampur   Hp37",
  "Rla Paonta Sahib   Hp17",
  "Rla Parwanoo   Hp15",
  "Rla Rajgarh   Hp16",
  "Rla Sarkaghat   Hp28",
  "Rla Shahpur   Hp90",
  "Rla Shri Naina Devi Ji Swarghat   Hp91",
  "Rla Solan   Hp14",
  "Rla Sujanpur   Hp84",
  "Rla Sundarnagar   Hp31",
  "Rla Theog   Hp9",
  "Rla Una   Hp20",
  "Rohini   Dl11",
  "Rohtak   Hr12",
  "Rohtas   Br24",
  "Roorkee Arto   Uk17",
  "Ropar   Pb12",
  "Rourkela Rto   Od14",
  "Rto Ahemednagar   Mh16",
  "Rto Akola   Mh30",
  "Rto Amritsar   Pb2",
  "Rto Baddi(Nalagarh)   Hp93",
  "Rto Barnala   Pb19",
  "Rto Bathinda   Pb3",
  "Rto Chandrapur   Mh34",
  "Rto Chamba   Hp73",
  "Rto Chennai (North West)   Tn2",
  "Rto Dharamshala   Hp68",
  "Rto Faridkot   Pb4",
  "Rto Ferozpur   Pb5",
  "Rto Gurdaspur   Pb6",
  "Rto Hamirpur   Hp67",
  "Rto Hoshiarpur   Pb7",
  "Rto Jalgaon   Mh19",
  "Rto Jalandhar   Pb8",
  "Rto Kapurthala   Pb9",
  "Rto Kullu   Hp66",
  "Rto Latur   Mh24",
  "Rto Ludhiana   Pb10",
  "Rto Madanapalle   Ap203",
  "Rto Mandi   Hp65",
  "Rto Nahan   Hp71",
  "Rto Patiala   Pb11",
  "Rto Pimpri Chinchwad   Mh14",
  "Rto Satara   Mh11",
  "Rto Shimla   Hp63",
  "Rto Solapur   Mh13",
  "Rto Una   Hp72",
  "Rto.Borivali   Mh47",
  "Sagar Arto   Ka15",
  "Sagar Rto   Mp15",
  "Saharanpur Rto   Up11",
  "Saharsa   Br19",
  "Sahjahanpur   Up27",
  "Sahapura (Bhilwara) Dto   Rj51",
  "Sahapura (Jaipur) Dto   Rj52",
  "Sahebganj   Jh18",
  "Salem (East) Rto   Tn54",
  "Salem (South) Rto   Tn90",
  "Salem (West) Rto   Tn30",
  "Salur Mvi Office   Ap235",
  "Samba Arto   Jk21",
  "Sambalpur Rto   Od15",
  "Sambhal Arto   Up38",
  "Samastipur   Br33",
  "Sankagiri Rto   Tn52",
  "Sankarankovil Rto   Tn610",
  "Sant Kabir Nagar   Up58",
  "Sathyamangalam Uo   Tn579",
  "Satna Arto   Mp19",
  "Sawai Madhopur Dto   Rj25",
  "Sdm Abohar   Pb15",
  "Sdm Ajnala   Pb14",
  "Sdm Amloh   Pb48",
  "Sdm Amritsar 2   Pb89",
  "Sdm Anandpur Sahib   Pb16",
  "Sdm Baba Bakala   Pb17",
  "Sdm Badhra   Hr88",
  "Sdm Badkhal   Hr87",
  "Sdm Badli   Hr89",
  "Sdm Badshahpur   Hr98",
  "Sdm Bagha Purana   Pb69",
  "Sdm Balachaur   Pb20",
  "Sdm Banga   Pb78",
  "Sdm Barwala   Hr80",
  "Sdm Bassi Pathana   Pb52",
  "Sdm Batala   Pb18",
  "Sdm Bhawnigarh   Pb84",
  "Sdm Bholath   Pb57",
  "Sdm Budhlada   Pb50",
  "Sdm Chamkaur Sahib   Pb71",
  "Sdm Dasuya   Pb21",
  "Sdm Dera Bassi   Pb70",
  "Sdm Dharamkot   Pb76",
  "Sdm Dhuri   Pb59",
  "Sdm Dinanagar   Pb99",
  "Sdm Dirba   Pb86",
  "Sdm Garshankar   Pb24",
  "Sdm Giddarbaha   Pb60",
  "Sdm Guru Har Sahai   Pb77",
  "Sdm Jagraon   Pb25",
  "Sdm Jaito   Pb62",
  "Sdm Jalalabad   Pb61",
  "Sdm Jalandhar 11   Pb90",
  "Sdm Khadur Sahib   Pb63",
  "Sdm Khamano   Pb49",
  "Sdm Khanna   Pb26",
  "Sdm Kharar   Pb27",
  "Sdm Kotkapura   Pb79",
  "Sdm Lehragaga   Pb75",
  "Sdm Malout   Pb53",
  "Sdm Maur Mandi   Pb80",
  "Sdm Moonak   Pb64",
  "Sdm Morinda   Pb87",
  "Sdm Mukerian   Pb54",
  "Sdm Nabha   Pb34",
  "Sdm Nakodar   Pb33",
  "Sdm Nangal   Pb74",
  "Sdm Nihal Singh Wala   Pb66",
  "Sdm Office Kalka   Hr49",
  "Sdm Patran   Pb72",
  "Sdm Patti   Pb38",
  "Sdm Payal   Pb55",
  "Sdm Phagwara   Pb36",
  "Sdm Phillour   Pb37",
  "Sdm Punhana   Hr93",
  "Sdm Raikot   Pb56",
  "Sdm Rajpura   Pb39",
  "Sdm Rampura Phul   Pb40",
  "Sdm Samana   Pb42",
  "Sdm Samrala   Pb43",
  "Sdm Sardulgarh   Pb51",
  "Sdm Shahabad   Hr78",
  "Sdm Shahkot   Pb67",
  "Sdm Sultanpur Lodhi   Pb41",
  "Sdm Sunam   Pb44",
  "Sdm Talwandi Sabo   Pb45",
  "Sdm Tapa   Pb73",
  "Sdm Uchana   Hr90",
  "Sdm Zira   Pb47",
  "Sehore Dto   Mp37",
  "Seoni Arto   Mp22",
  "Shahdol Rto   Mp18",
  "Shahpur   Hp90",
  "Shajapur Dto   Mp42",
  "Shamli Arto   Up19",
  "Sheikhpura   Br52",
  "Sheohar   Br55",
  "Shillong   Ml5",
  "Shimoga Rto   Ka14",
  "Shivpuri Dto   Mp33",
  "Sholinganallur Rto   Tn512",
  "Shravasti   Up46",
  "Siddharth Nagar(Naugarh)   Up55",
  "Sidhi Dto   Mp53",
  "Sikar Rto   Rj23",
  "Siliguri Arto   Wb73",
  "Silvassa   Dd1",
  "Simdega   Jh20",
  "Singroli Dto   Mp66",
  "Sirkali Uo   Tn623",
  "Sirohi Dto   Rj24",
  "Sirsa   Hr24",
  "Sivagangai Rto   Tn63",
  "Sivakasi Rto   Tn604",
  "Sivasagar   As4",
  "Siwan   Br29",
  "Sonbhadra   Up64",
  "Sonepat   Hr10",
  "Sonepur Rto   Od31",
  "South Delhi   Dl3",
  "South Tripura Dto   Tr8",
  "Sri Ganganagar Dto   Rj13",
  "Srikakulam Rta   Ap30",
  "Sriperumbudur Rto   Tn614",
  "Srirampur   Mh17",
  "Srirampur Arto   Wb17",
  "Srivilliputhur Rto   Tn605",
  "Subarnapur Rto   Od31",
  "Sujangarh Dto   Rj44",
  "Sukma Dto   Cg26",
  "Sulthanbathery Srto   Kl73",
  "Sullurpet Uo   Ap426",
  "Sulur Uo   Tn620",
  "Sumerpur Dto   Rj57",
  "Sundarnagar   Hp31",
  "Sundergarh Rto   Od16",
  "Surajmal Vihar   Dl13",
  "Surajpur Dto   Cg29",
  "Surat   Gj5",
  "Surendranagar   Gj13",
  "Tadepalli Gudem Uo   Ap437",
  "Tadipatri Uo   Ap402",
  "Talcher Rto   Od35",
  "Tamluk Rto   Wb29",
  "Tanakpur Arto   Uk3",
  "Tapi   Gj26",
  "Tarikere, Chikkamagaluru Arto   Ka66",
  "Tenkasi Rto   Tn76",
  "Thalassery Srto   Kl58",
  "Thaliparamba Srto   Kl59",
  "Thane   Mh4",
  "Thanesar   Hr7",
  "Thanjavur Rto   Tn49",
  "Theni Rto   Tn60",
  "Theog   Hp9",
  "Thiruchendur Rto   Tn606",
  "Thirukalukuntram Uo   Tn639",
  "Thirumangalam Uo   Tn598",
  "Thirupattur Rto   Tn624",
  "Thiruthuraipoondi Uo   Tn630",
  "Thiruttani Uo   Tn634",
  "Thiruvalla Srto   Kl27",
  "Thodupuzha Srto   Kl38",
  "Thoothukudi Rto   Tn69",
  "Thoubal   Mn4",
  "Thuraiyur Uo   Tn586",
  "Tikamgarh Dto   Mp36",
  "Tindivanam Rto   Tn571",
  "Tinsukia   As23",
  "Tiptur Arto   Ka44",
  "Tiruchengode Rto   Tn34",
  "Tiruchi Rto   Tn45",
  "Tiruchi(East) Rto   Tn81",
  "Tirunelveli Rto   Tn72",
  "Tiruppur (North) Rto   Tn39",
  "Tiruppur (South) Rto   Tn42",
  "Tiruvallur Rto   Tn20",
  "Tiruvannamalai Rto   Tn25",
  "Tiruvarur Rto   Tn50",
  "Tiruveranbur Uo   Tn583",
  "Tonk Dto   Rj26",
  "Transport Nagar Rto Lucknow (Up32)   Up32",
  "Trivandrum Rto   Kl1",
  "Tumkur Rto   Ka6",
  "Udaipur Rto   Rj27",
  "Udalguri   As27",
  "Udgir   Mh55",
  "Udhampur Arto   Jk14",
  "Udham Singh Nagar Arto   Uk6",
  "Udupi Rto   Ka20",
  "Udumalpet Rto   Tn581",
  "Uluberia Arto   Wb13",
  "Ulundurpet Rto   Tn577",
  "Ujjain Rto   Mp13",
  "Umaria Dto   Mp54",
  "Unakoti Dto   Tr2",
  "Unit Office Kathipudi   Ap305",
  "Unit Office Rayadurg   Ap502",
  "Unnao   Up35",
  "Usilampatti Uo   Tn636",
  "Uthamapalayam Uo   Tn601",
  "Uttar Dinajpur Rto   Wb59",
  "Uttarkashi Arto   Uk10",
  "Uzhavoor Srto   Kl67",
  "Vadakara Rto   Kl18",
  "Vadipatti Uo   Tn599",
  "Vaijapur   Mh57",
  "Vaikom Srto   Kl36",
  "Vaishali   Br31",
  "Valappadi Uo   Tn613",
  "Valliyur Uo   Tn608",
  "Valsad   Gj15",
  "Vandiperiyar Srto   Kl37",
  "Vaniyambadi Rto   Tn515",
  "Varanasi Rto   Up65",
  "Vasco Rto   Ga6",
  "Vashi (New Mumbai)   Mh43",
  "Vasant Vihar   Dl12",
  "Vedachandur Uo   Tn617",
  "Vellarikundu Srto   Kl79",
  "Vellore Rto   Tn23",
  "Veraval   Gj32",
  "Vidisha Dto   Mp40",
  "Vijayawada Rta   Ap16",
  "Vikas Nagar Arto   Uk16",
  "Viluppuram Rto   Tn32",
  "Virudhachalam Uo   Tn553",
  "Virudhunagar Rto   Tn67",
  "Vishakapatnam Rta   Ap31",
  "Vizianagaram Rta   Ap35",
  "Vuyyuru Uo   Ap516",
  "Wadakkancherry Srto   Kl48",
  "Wardha   Mh32",
  "Washim   Mh37",
  "Wazirpur   Dl8",
  "West Singhbhum (Chaibasa)   Jh6",
  "West Tripura Jtc   Tr1",
  "Yadgiri Rto   Ka33",
  "Yalahanka Rto   Ka50",
  "Yamunanagar   Hr2",
  "Yanam   Py4"
].sort();

  return (
    <div className="min-h-screen bg-neutral-50">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <header className="bg-white border-b border-neutral-200 shadow-sm">
          <div className="px-6 py-4">
            <div className="flex items-center justify-between w-full">
              {/* Left: Logo and Titles */}
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-primary rounded-lg flex items-center justify-center">
                  <ChartLine className="text-white text-lg" />
                </div>
                <div>
                  <h1 className="text-xl font-bold text-neutral-900">Sales Analytics</h1>
                  <p className="text-sm text-neutral-500">India Market Intelligence Platform</p>
                </div>
              </div>
              {/* Right: Export Report and User Icon */}
              <div className="flex items-center space-x-4 ml-auto">
                <Button variant="outline" className="text-sm font-medium">
                  <Download className="mr-2 h-4 w-4" />
                  Export Report
                </Button>
                <div className="w-8 h-8 bg-neutral-300 rounded-full flex items-center justify-center">
                  <User className="text-neutral-600 text-sm" />
                </div>
              </div>
            </div>
          </div>
        </header>

        {/* Main Dashboard */}
        <main className="px-8 py-8">
          {/* Executive Metrics Overview */}
          <MetricsOverview />

          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
            {/* Data Upload and Controls */}
            <div className="lg:col-span-1 space-y-6">
              <MapControls
                viewMode={viewMode}
                onViewModeChange={setViewMode}
                showLabels={showLabels}
                onShowLabelsChange={setShowLabels}
              />
              {/* Years Checklist Dropdown */}
              <div className="min-w-[180px] flex items-end gap-2">
                <div className="w-full">
                  <label className="block text-sm font-medium text-neutral-700 mb-2">Years</label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="outline" className="w-full justify-between">
                        {selectedYears.length === 0 ? 'Select Years' : selectedYears.length === yearOptions.length ? 'All' : `${selectedYears.length} selected`}
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent className="max-h-72 overflow-y-auto w-full min-w-[180px]" onCloseAutoFocus={e => e.preventDefault()}>
                      <DropdownMenuCheckboxItem
                        checked={selectedYears.length === 0}
                        onCheckedChange={checked => {
                          setSelectedYears(checked ? yearOptions : []);
                        }}
                        onSelect={e => e.preventDefault()}
                      >
                        All
                      </DropdownMenuCheckboxItem>
                      {yearOptions.map(year => (
                        <DropdownMenuCheckboxItem
                          key={year}
                          checked={selectedYears.includes(year)}
                          onCheckedChange={checked => {
                            setSelectedYears(checked
                              ? [...selectedYears, year]
                              : selectedYears.filter(y => y !== year)
                            );
                          }}
                          onSelect={e => e.preventDefault()}
                        >
                          {year}
                        </DropdownMenuCheckboxItem>
                      ))}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
                <Button
                  className="h-10 ml-2"
                  variant="default"
                  onClick={() => setSelectedYears(selectedYears)}
                  disabled={selectedYears.length === 0}
                >
                  Apply Filters
                </Button>
              </div>
              {/* FileUpload */}
              <FileUpload />
            </div>

            {/* Map Visualization and Filters */}
            <div className="lg:col-span-3 flex flex-col gap-6">
              {/* Dynamic Cascading Filters */}
              <div className="bg-white p-4 rounded-lg shadow-sm mb-4">
                <h3 className="text-sm font-medium text-neutral-700 mb-3">Filter by Excel Data</h3>
                <CascadingFilters 
                  onFiltersChange={(data) => {
                    setFilteredSalesData(data);
                  }}
                  selectedMakers={selectedMakers}
                  selectedRTOs={selectedRTOs}
                  selectedStates={selectedStates}
                  selectedDistricts={selectedDistricts}
                  onMakersChange={setSelectedMakers}
                  onRTOsChange={setSelectedRTOs}
                  onStatesChange={setSelectedStates}
                  onDistrictsChange={setSelectedDistricts}
                />
                </div>

              {/* Map Visualization */}
              <MapVisualization 
                selectedYears={selectedYears}
                selectedMonths={selectedMonths}
                selectedMakers={selectedMakers}
                selectedRTOs={selectedRTOs}
                selectedStates={selectedStates}
                selectedDistricts={selectedDistricts}
                viewMode={viewMode}
                showLabels={showLabels}
                filteredData={filteredSalesData}
              />
            </div>
          </div>

          {/* Data Table */}
          <DataTable 
            selectedYears={selectedYears} 
            selectedMakers={selectedMakers} 
            selectedRTOs={selectedRTOs} 
            selectedMonths={selectedMonths}
            selectedStates={selectedStates}
            selectedDistricts={selectedDistricts}
          />
        </main>
      </div>
    </div>
  );
}
